import psycopg2
from psycopg2 import Error

try:
    connection = psycopg2.connect(
        host='localhost', 
        database='PhoneBook',
        user='postgres',
        password='zhuka'
    )

    cursor = connection.cursor()
    # хранимая процедура
    cursor.callproc('pattern')
    result = cursor.fetchall()
    for row in result:
        print("number = ", row[0])
        print("username = ", row[1])
        print("telephone_number = ", row[2])
        print("city =", row[3])
        print("age =", row[4])

except (Exception, Error) as error:
    print("ERROR", error)
finally:
    if connection:
        cursor.close()
        connection.close()
